services:
  sgx-scaffold-builder:
    image: ghcr.io/automata-network/sgx-scaffold:ubuntu-20.04_sgx-2.24
    build:
      context: ./../../
      dockerfile: ./docker/ubuntu-20.04/Dockerfile

  sgx-scaffold:
    image: ghcr.io/automata-network/sgx-scaffold:ubuntu-20.04_sgx-2.24
    container_name: sgx-scaffold
    privileged: true
    environment:
      - AZDCAP_BYPASS_BASE_URL=${AZDCAP_BYPASS_BASE_URL:-true}
      - AZDCAP_DEBUG_LOG_LEVEL=${AZDCAP_DEBUG_LOG_LEVEL:-ERROR1}
    volumes:
      - /dev/sgx_provision:/dev/sgx_provision
      - /dev/sgx:/dev/sgx
      - /dev/sgx_enclave:/dev/sgx_enclave
    working_dir: /workspace
